### ISSUE TITLE
Please public 0.0.2

### ISSUE THREAD

**Issue by philips** [tjfontaine/node-struct#1]
I was trying to play with node-dns and pystruct 0.0.2 isn't published to npm. Fixed via:
diff --git a/package.json b/package.json
index 9c50eed..d4d2290 100644
--- a/package.json
+++ b/package.json
@@ -24,6 +24,6 @@
     "bufferjs": ">= 1.0.0",
     "clone": ">= 0.0.4",
     "ipaddr.js": ">= 0.1.0",
-    "pystruct": ">= 0.0.2"
-    "pystruct": "https://github.com/tjfontaine/node-struct/tarball/master"
  }
  }

**Comment by tjfontaine** [comment]
I can publish this, but I was holding off until I finish the next release of node-dns, if I don't achieve that tonight I will publish an update for pystruct

**Comment by tjfontaine** [comment]
I have published pystruct 0.0.2 please let me know if you have any issues.

**Comment by philips** [comment]
Great! Thanks for the fast response. The native-dns library is great.
